(defmodule docs-dev
  (export all))

(defun start-httpd (cfg)
  (logjam:info "Starting dev HTTP server ...")
  (logjam:debug "Using config: ~n~p" `(,cfg))
  (let ((doc-root (filename:absname (docs-cfg:get-in '(site-gen build-dir) cfg)))
        (port (docs-cfg:get-in '(site-gen dev-server port) cfg)))
    (inets:start 'httpd `(#(server_name "devdocs")
                          #(document_root ,doc-root)
                          #(server_root ,doc-root)
                          #(port ,port)
                          #(mime-types (#("html" "text/plain")
                                        #("htm" "text/plain")
                                        #("js" "text/javascript")
                                        #("css" "text/css")
                                        #("png" "image/png")
                                        #("jpeg" "image/jpeg")
                                        #("jpg" "image/jpeg")))))))
